# Site settings
title_left    : "5"
title_right   : " Error" # default: ""
description   : "Software, stories, and the world they're built in."
keywords      : "thoughts, stories, ideas, software, ghana, afradio, culture, thinkspace"
url           : "" # https://5Error.com # site url
baseurl       : "" # apply repo name like "/myproject" if used under gh-pages branch, else (under master branch) just leave empty/blank
cover         : "" # image uri like logo/cover image for site seo

google_analytics  : UA-137058486-1
twitter_username  : "KiddBubu"
comments_enabled  : true
giscus:
  repo            : "bubunyo/bubunyo.github.io"
  repo_id         : "MDEwOlJlcG9zaXRvcnkxNzgyNTU1Njg"          # paste from giscus.app
  category        : "General"          # paste from giscus.app
  category_id     : "DIC_kwDOCp_20M4C3ahA"          # paste from giscus.app
  theme           : "light"
  lang            : "en"
postshare_enabled : true

# Build settings
permalink   : /:title/
markdown    : kramdown
highlighter : rouge

source      : ./
destination : ./_site

# Sass configuration
sass:
  sass_dir  : assets/scss
  style     : compressed # expanded

# Author settings
author:
  name     : "Bubunyo Nyavor"

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md", "script", "vendor"]
